// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iiygawyihmxqffigfejr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpeWdhd3lpaG14cWZmaWdmZWpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNjIyNDAsImV4cCI6MjA2MDkzODI0MH0.D160otCpGCxVNqaLQZ0Q_yIaVX7JKTOMFcgRETjIUSI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);